// ============================================================
// Seed data — tuned to Shank's physique priorities:
// 1 Upper Chest · 2 Side Delts · 3 Lats · 4 Rear Delts
// 5 Arms · 6 Upper Back · 7 Waist Reduction · 8 Legs (maintain+grow)
// ============================================================
import type {
  AchievementDef,
  AppState,
  Exercise,
  Profile,
  RoadmapGoal,
  WorkoutDay,
} from "./types";

import { LIBRARY_EXERCISES } from "./library";
import { VIDEO_IDS } from "./video-ids";

const yt = (q: string) =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " proper form")}`;

const CURATED_EXERCISES: Exercise[] = [
  // ---------- CHEST (upper-chest priority) ----------
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    primary: "Upper Chest",
    secondary: ["Front Delts", "Triceps"],
    equipment: "Dumbbell",
    videoUrl: yt("incline dumbbell press"),
    cues: ["Bench at 30°", "Elbows at 45° to torso", "Press up and slightly back", "Full stretch at bottom"],
    mistakes: ["Bench too steep (becomes shoulders)", "Flaring elbows to 90°", "Cutting range short at the bottom"],
    alternatives: ["Incline Barbell Press", "Incline Machine Press", "Low-to-High Cable Fly"],
    progression: "Hit 3×10 with control → add 2 kg per dumbbell",
    incrementKg: 2,
    home: {
      name: "Decline Push-Up",
      reps: "3×8–15",
      how: "Feet elevated, hands slightly wider than shoulders — the higher the feet, the more upper chest. When 15 clean reps get easy: 3-sec negatives, then add a 2-sec pause at the bottom.",
    },
  },
  {
    id: "incline-bb-press",
    name: "Incline Barbell Press",
    primary: "Upper Chest",
    secondary: ["Front Delts", "Triceps"],
    equipment: "Barbell",
    videoUrl: yt("incline barbell bench press"),
    cues: ["Grip slightly wider than shoulders", "Touch bar to upper chest", "Drive feet into floor"],
    mistakes: ["Bouncing bar off chest", "Half reps", "Wrists bent back"],
    alternatives: ["Incline Dumbbell Press", "Smith Incline Press"],
    progression: "3×8 clean reps → add 2.5 kg",
    incrementKg: 2.5,
    home: {
      name: "Paused Decline Push-Up",
      reps: "3×6–12",
      how: "Feet elevated, full 2-sec stop at the bottom with the chest just off the mat, then press up and slightly back — same bar path. The dead pause replaces the extra plates.",
    },
  },
  {
    id: "flat-bb-bench",
    name: "Flat Barbell Bench Press",
    primary: "Mid Chest",
    secondary: ["Front Delts", "Triceps"],
    equipment: "Barbell",
    videoUrl: yt("barbell bench press"),
    cues: ["Shoulder blades pinched", "Slight arch", "Bar path over lower chest", "Elbows ~60–70°"],
    mistakes: ["Flat shoulder blades (shoulder strain)", "Bouncing", "Uneven lockout"],
    alternatives: ["Flat Dumbbell Press", "Machine Chest Press"],
    progression: "3×8 → add 2.5 kg. Milestone: 60 kg × 8",
    incrementKg: 2.5,
    home: {
      name: "Push-Up → Archer Push-Up",
      reps: "3×10–20",
      how: "Standard push-up: body in one line, elbows ~60°, chest to the mat. Past 20 easy reps, go archer — hands wide, bend one elbow while the other arm stays straight. One side does the pressing.",
    },
  },
  {
    id: "cable-fly-low-high",
    name: "Low-to-High Cable Fly",
    primary: "Upper Chest",
    secondary: ["Front Delts"],
    equipment: "Cable",
    videoUrl: yt("low to high cable fly"),
    cues: ["Pulleys at lowest setting", "Scoop up and in", "Squeeze at eye level", "Slow negative"],
    mistakes: ["Turning it into a press", "Too heavy — momentum", "Shrugging shoulders"],
    alternatives: ["Incline Dumbbell Fly", "Pec Deck (seat low)"],
    progression: "3×12 with 2-sec squeeze → next pin",
    incrementKg: 2.5,
    home: {
      name: "Squeeze Decline Push-Up",
      reps: "3×8–12",
      how: "Feet elevated, hands set wide. As you press, actively drag the palms toward each other — the hands don't move, but the pecs contract exactly like a fly. Hold the squeeze 2 sec at the top.",
    },
  },
  {
    id: "dips",
    name: "Chest Dips",
    primary: "Mid Chest",
    secondary: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    videoUrl: yt("chest dips"),
    cues: ["Lean torso forward", "Elbows slightly flared", "Deep stretch, don't bounce"],
    mistakes: ["Staying upright (all triceps)", "Shoulders rolling forward at bottom"],
    alternatives: ["Assisted Dip Machine", "Decline Push-ups"],
    progression: "3×12 bodyweight → add weight with belt",
    incrementKg: 2.5,
    isBodyweight: true,
    home: {
      name: "Pseudo-Planche Push-Up",
      reps: "3×6–12",
      how: "Hands beside the lower ribs with fingers pointing toward your feet, shoulders leaning far past the wrists, then press. That forward lean is the exact reason dips grow chest.",
    },
  },
  // ---------- SHOULDERS (side + rear delt priority) ----------
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    primary: "Side Delts",
    secondary: ["Traps"],
    equipment: "Dumbbell",
    videoUrl: yt("dumbbell lateral raise"),
    cues: ["Lead with elbows", "Pinky slightly up at top", "Raise to shoulder height", "Control the negative"],
    mistakes: ["Swinging with momentum", "Shrugging traps", "Going above shoulder height"],
    alternatives: ["Cable Lateral Raise", "Machine Lateral Raise"],
    progression: "3×15 strict → add 1–2 kg. Volume is king here",
    incrementKg: 1,
    home: {
      name: "Wide-Elbow Pike Push-Up",
      reps: "3×8–12",
      how: "Hips high in a folded V, hands wider than shoulders, elbows flaring straight out to the sides so the delts drive the press. Elevate the feet to load it further.",
    },
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    primary: "Side Delts",
    secondary: [],
    equipment: "Cable",
    videoUrl: yt("cable lateral raise behind back"),
    cues: ["Cable behind body", "Constant tension bottom to top", "Slight lean away from stack"],
    mistakes: ["Standing too close to pulley", "Jerking the start"],
    alternatives: ["Dumbbell Lateral Raise", "Lying Incline Lateral Raise"],
    progression: "3×15 → next pin",
    incrementKg: 2.5,
    home: {
      name: "Wall Handstand Hold",
      reps: "3×20–40 sec",
      how: "Kick up against the wall, arms locked, push tall through the shoulders the whole hold. Your entire bodyweight sits on the delts. Progress with slow shoulder taps.",
    },
  },
  {
    id: "db-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    primary: "Front Delts",
    secondary: ["Side Delts", "Triceps"],
    equipment: "Dumbbell",
    videoUrl: yt("seated dumbbell shoulder press"),
    cues: ["Back supported", "Elbows slightly in front", "Press to full lockout"],
    mistakes: ["Excessive lower-back arch", "Half lockout", "Elbows flared fully sideways"],
    alternatives: ["Machine Shoulder Press", "Overhead Barbell Press"],
    progression: "3×10 → add 2 kg per dumbbell",
    incrementKg: 2,
    home: {
      name: "Pike Push-Up",
      reps: "3×8–12",
      how: "Hips high in a folded V, hands shoulder-width. Lower the crown of your head to the mat and press back up. Elevating the feet moves it closer to a handstand push-up.",
    },
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    primary: "Rear Delts",
    secondary: ["Upper Back"],
    equipment: "Machine",
    videoUrl: yt("reverse pec deck rear delt"),
    cues: ["Arms slightly bent, fixed", "Pull with elbows, not hands", "Pause 1 sec at back"],
    mistakes: ["Using traps/rhomboids by squeezing blades", "Too heavy, short ROM"],
    alternatives: ["Bent-over DB Reverse Fly", "Face Pulls"],
    progression: "3×15 with pause → next pin",
    incrementKg: 2.5,
    home: {
      name: "Prone T-Raise",
      reps: "3×15–20",
      how: "Lie face-down, arms out in a T, thumbs up. Lift the arms toward the ceiling and pause 1 sec — pull with the rear delts, not by pinching the blades. Progress with a 3-sec hold at the top.",
    },
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    primary: "Rear Delts",
    secondary: ["Upper Back", "Traps"],
    equipment: "Cable",
    videoUrl: yt("cable face pull"),
    cues: ["Rope at upper-chest height", "Pull to forehead, elbows high", "External rotate at end"],
    mistakes: ["Pulling to chest (becomes a row)", "Leaning back heavily"],
    alternatives: ["Reverse Pec Deck", "Band Pull-aparts"],
    progression: "3×15 → next pin. Also your shoulder-health insurance",
    incrementKg: 2.5,
    home: {
      name: "Prone Y-W Swimmers",
      reps: "3×12–15",
      how: "Lie face-down, chest slightly lifted. Start with elbows bent in a W, squeeze the rear delts, then reach overhead to a Y and pull back to W — arms never touch the mat during the set.",
    },
  },
  // ---------- BACK (lats + upper back priority) ----------
  {
    id: "pullup",
    name: "Pull-up",
    primary: "Lats",
    secondary: ["Biceps", "Upper Back"],
    equipment: "Bodyweight",
    videoUrl: yt("pull up"),
    cues: ["Grip slightly wider than shoulders", "Depress shoulder blades first", "Chest to bar, elbows down"],
    mistakes: ["Kipping/swinging", "Chin-poking half reps", "No scapular control"],
    alternatives: ["Lat Pulldown", "Assisted Pull-up Machine", "Band-assisted Pull-up"],
    progression: "Assisted → bodyweight singles → 3×8 → weighted",
    incrementKg: 2.5,
    isBodyweight: true,
    home: {
      name: "Pull-Up — same bar at home",
      reps: "3×5–8",
      how: "You have the bar, so the exercise travels with you unchanged. Not at full reps yet? Jump to the top and lower for 5 sec — slow negatives are what build the first strict pull-up.",
    },
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primary: "Lats",
    secondary: ["Biceps", "Upper Back"],
    equipment: "Machine",
    videoUrl: yt("lat pulldown"),
    cues: ["Slight lean back (~15°)", "Pull bar to upper chest", "Drive elbows down and back", "Full stretch up top"],
    mistakes: ["Pulling behind neck", "Using body swing", "Half stretch at top"],
    alternatives: ["Pull-up", "Single-arm Cable Pulldown"],
    progression: "3×10 → +5 kg plate. Milestone: 45 kg",
    incrementKg: 5,
    home: {
      name: "Negative Pull-Up",
      reps: "3×4–6",
      how: "Jump to the top of your bar, hold 1 sec with the chest up, then lower for a full 5 count — elbows down and back exactly like the pulldown. Own the negative and full reps follow.",
    },
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    primary: "Upper Back",
    secondary: ["Lats", "Biceps"],
    equipment: "Cable",
    videoUrl: yt("seated cable row"),
    cues: ["Chest tall", "Pull to belly button", "Squeeze blades 1 sec", "Stretch forward under control"],
    mistakes: ["Rocking torso back and forth", "Shrugging", "Rounding lower back on stretch"],
    alternatives: ["Chest-supported Row", "Single-arm DB Row"],
    progression: "3×10 → +5 kg",
    incrementKg: 5,
    home: {
      name: "Superman Row",
      reps: "3×12–15",
      how: "Lie face-down with chest lifted and arms reaching forward. Pull the elbows back to your ribs and squeeze the blades 1 sec, then reach forward again — no resting on the mat between reps.",
    },
  },
  {
    id: "single-arm-db-row",
    name: "Single-arm Dumbbell Row",
    primary: "Lats",
    secondary: ["Upper Back", "Biceps"],
    equipment: "Dumbbell",
    videoUrl: yt("single arm dumbbell row"),
    cues: ["Flat back, knee on bench", "Row towards hip pocket", "Full stretch at bottom"],
    mistakes: ["Rotating torso", "Rowing to shoulder (traps take over)"],
    alternatives: ["Barbell Row", "Chest-supported Row"],
    progression: "3×10/side → +2 kg",
    incrementKg: 2,
    home: {
      name: "Side-to-Side Pull-Up",
      reps: "3×3–6 / side",
      how: "On your bar, pull the chin toward one hand, lower under control, then pull toward the other. Each side carries most of the load — the closest bodyweight match to a one-arm row.",
    },
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-arm Pulldown",
    primary: "Lats",
    secondary: [],
    equipment: "Cable",
    videoUrl: yt("straight arm cable pulldown"),
    cues: ["Arms nearly straight", "Sweep bar to thighs", "Feel the lat stretch at top"],
    mistakes: ["Bending elbows (becomes a pushdown)", "Hunching over"],
    alternatives: ["Dumbbell Pullover", "Machine Pullover"],
    progression: "3×12 → next pin. Great lat isolation without biceps stealing",
    incrementKg: 2.5,
    home: {
      name: "Hanging Scapular Pull",
      reps: "3×8–12",
      how: "Dead-hang from your bar with straight arms, then pull the shoulder blades down so the body rises a few centimetres — no elbow bend. Pause 2 sec. That motion IS the straight-arm pulldown.",
    },
  },
  // ---------- ARMS ----------
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curl",
    primary: "Biceps",
    secondary: ["Forearms"],
    equipment: "Barbell",
    videoUrl: yt("ez bar curl"),
    cues: ["Elbows pinned to sides", "Full extension at bottom", "Squeeze at top"],
    mistakes: ["Swinging hips", "Elbows drifting forward", "Half reps"],
    alternatives: ["Dumbbell Curl", "Cable Curl"],
    progression: "3×10 → +2.5 kg",
    incrementKg: 2.5,
    home: {
      name: "Chin-Up (underhand)",
      reps: "3×5–10",
      how: "Shoulder-width underhand grip on your bar, pull until the chin clears, control the way down. Biceps take most of the load. Not there yet? 5-sec negatives until you are.",
    },
  },
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    primary: "Biceps",
    secondary: [],
    equipment: "Dumbbell",
    videoUrl: yt("incline dumbbell curl"),
    cues: ["Bench at 55–60°", "Arms hang behind torso", "Curl without moving elbows"],
    mistakes: ["Bringing elbows forward", "Rushing the negative"],
    alternatives: ["Bayesian Cable Curl", "Preacher Curl"],
    progression: "3×10 → +1–2 kg. Best long-head stretch",
    incrementKg: 1,
    home: {
      name: "Dead-Stop Chin-Up",
      reps: "3×4–8",
      how: "Every rep starts from a full dead hang, arms completely straight — the same stretched position this curl is built for. Pull with zero swing, lower to a dead stop, repeat.",
    },
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    primary: "Biceps",
    secondary: ["Forearms"],
    equipment: "Dumbbell",
    videoUrl: yt("hammer curl"),
    cues: ["Neutral grip", "Control both directions"],
    mistakes: ["Swinging", "Elbow drift"],
    alternatives: ["Rope Hammer Curl", "Reverse Curl"],
    progression: "3×12 → +2 kg. Builds arm thickness",
    incrementKg: 2,
    home: {
      name: "Neutral-Grip Chin + Dead Hang",
      reps: "3×5–10 + hang",
      how: "Use the parallel handles if your bar has them (underhand works if not) — the neutral grip is exactly the hammer position. Finish each set with a max-time dead hang for grip and forearms.",
    },
  },
  {
    id: "triceps-pushdown",
    name: "Cable Triceps Pushdown",
    primary: "Triceps",
    secondary: [],
    equipment: "Cable",
    videoUrl: yt("cable triceps pushdown rope"),
    cues: ["Elbows pinned", "Full lockout, split rope at bottom", "Slow return"],
    mistakes: ["Leaning over the cable", "Elbows flaring out"],
    alternatives: ["Bar Pushdown", "Bench Dips"],
    progression: "3×12 → next pin",
    incrementKg: 2.5,
    home: {
      name: "Diamond Push-Up",
      reps: "3×8–15",
      how: "Hands close with thumbs and index fingers touching, elbows tracking back along the ribs. Lock out hard at the top of every rep — that's the pushdown squeeze.",
    },
  },
  {
    id: "overhead-triceps-ext",
    name: "Overhead Cable Triceps Extension",
    primary: "Triceps",
    secondary: [],
    equipment: "Cable",
    videoUrl: yt("overhead cable triceps extension"),
    cues: ["Elbows close to head", "Deep stretch behind head", "Extend to lockout"],
    mistakes: ["Elbows flaring wide", "Short ROM"],
    alternatives: ["DB Overhead Extension", "Skull Crushers"],
    progression: "3×12 → next pin. Long-head = arm size",
    incrementKg: 2.5,
    home: {
      name: "Sphinx Push-Up",
      reps: "3×6–12",
      how: "Start in a forearm plank, press up onto the palms by extending only the elbows, lower the forearms back down with control. A bodyweight skull crusher — all triceps, long head under stretch.",
    },
  },
  // ---------- LEGS (maintain + grow) ----------
  {
    id: "squat",
    name: "Barbell Back Squat",
    primary: "Quads",
    secondary: ["Glutes", "Hamstrings", "Lower Back"],
    equipment: "Barbell",
    videoUrl: yt("barbell back squat"),
    cues: ["Bar on traps, brace core", "Sit down between heels", "Depth: hip crease below knee", "Drive knees out"],
    mistakes: ["Knees caving in", "Heels lifting", "Good-morning squat (hips shoot up)"],
    alternatives: ["Hack Squat", "Leg Press", "Goblet Squat"],
    progression: "3×8 → +2.5–5 kg",
    incrementKg: 2.5,
    home: {
      name: "Tempo Squat → Pistol Progression",
      reps: "3×10–20",
      how: "3 sec down, 1-sec pause at the bottom, drive up. When 20 are easy, move to split squats, then pistol progressions — one leg out front, sit back slow, stand. No load needed for a long time.",
    },
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primary: "Quads",
    secondary: ["Glutes"],
    equipment: "Machine",
    videoUrl: yt("leg press"),
    cues: ["Feet shoulder width, mid platform", "Lower until 90°+ knee bend", "Don't lock knees hard"],
    mistakes: ["Butt lifting off pad", "Tiny half reps with ego weight"],
    alternatives: ["Hack Squat", "Squat"],
    progression: "3×10 → +10 kg",
    incrementKg: 10,
    home: {
      name: "Reverse Lunge",
      reps: "3×10–12 / side",
      how: "Step back into a lunge, front shin vertical, rear knee kissing the mat, then drive through the front heel to stand. 3-sec descents; never let the knee cave in.",
    },
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    primary: "Hamstrings",
    secondary: ["Glutes", "Lower Back"],
    equipment: "Barbell",
    videoUrl: yt("romanian deadlift"),
    cues: ["Soft knees, hips back", "Bar drags along thighs", "Stretch hamstrings, stop mid-shin", "Flat back always"],
    mistakes: ["Rounding back", "Bending knees too much (becomes squat)", "Bar drifting away"],
    alternatives: ["DB RDL", "Seated Leg Curl"],
    progression: "3×10 → +2.5–5 kg",
    incrementKg: 2.5,
    home: {
      name: "Single-Leg Hip Hinge",
      reps: "3×10–12 / side",
      how: "On one leg, arms reaching forward as the counterweight, push the hips back with a flat back until the hamstring stretches, stand tall by squeezing the glute. Slow and strict — the balance is part of the work.",
    },
  },
  {
    id: "leg-curl",
    name: "Seated Leg Curl",
    primary: "Hamstrings",
    secondary: [],
    equipment: "Machine",
    videoUrl: yt("seated leg curl"),
    cues: ["Full stretch at top", "Squeeze hard at bottom", "Slow negative"],
    mistakes: ["Hips lifting", "Partial reps"],
    alternatives: ["Lying Leg Curl", "Nordic Curl"],
    progression: "3×12 → next pin",
    incrementKg: 5,
    home: {
      name: "Glute-Bridge Walkout",
      reps: "3×8–12",
      how: "Bridge the hips up, then walk the heels out step by step until the legs are nearly straight, and walk them back — hips never drop. Hamstrings work every centimetre of the way.",
    },
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primary: "Quads",
    secondary: [],
    equipment: "Machine",
    videoUrl: yt("leg extension"),
    cues: ["Toes up", "Pause 1 sec at top", "Control down"],
    mistakes: ["Swinging weight up", "Hips lifting off seat"],
    alternatives: ["Sissy Squat", "Front Squat"],
    progression: "3×12 → next pin",
    incrementKg: 5,
    home: {
      name: "Reverse Nordic",
      reps: "3×8–12",
      how: "Kneel on the mat, body in one straight line from knees to head, lean back as far as the quads allow, then pull yourself upright. Pure knee extension — start shallow, it bites.",
    },
  },
  {
    id: "calf-raise",
    name: "Standing Calf Raise",
    primary: "Calves",
    secondary: [],
    equipment: "Machine",
    videoUrl: yt("standing calf raise"),
    cues: ["Deep stretch at bottom, 2 sec", "Full rise onto toes", "No bouncing"],
    mistakes: ["Bouncing out of the stretch", "Partial ROM"],
    alternatives: ["Seated Calf Raise", "Leg-press Calf Raise"],
    progression: "3×15 → +5 kg",
    incrementKg: 5,
    home: {
      name: "Single-Leg Calf Raise",
      reps: "3×15–20 / side",
      how: "One foot at a time — full rise onto the toe, 2-sec squeeze at the top, slow down. Ball of the foot on the edge of whatever elevates your feet for push-ups gives the deep stretch back.",
    },
  },
  // ---------- CORE (waist priority = keep it tight, don't thicken obliques) ----------
  {
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    primary: "Abs",
    secondary: [],
    equipment: "Bodyweight",
    videoUrl: yt("hanging knee raise"),
    cues: ["Curl pelvis up, don't just lift legs", "Slow negative", "No swinging"],
    mistakes: ["Swinging momentum", "Hip-flexor-only reps"],
    alternatives: ["Lying Leg Raise", "Cable Crunch"],
    progression: "3×12 → straighten legs → hanging leg raise",
    incrementKg: 0,
    isBodyweight: true,
    home: {
      name: "Hanging Knee Raise — same bar",
      reps: "3×10–15",
      how: "Your pull-up bar does this one at home unchanged — curl the pelvis, no swinging. No room to hang? Lying leg raises on the mat with a 3-sec negative hit the same curl.",
    },
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    primary: "Abs",
    secondary: [],
    equipment: "Cable",
    videoUrl: yt("kneeling cable crunch"),
    cues: ["Crunch spine, not hips", "Elbows to knees", "Exhale hard at bottom"],
    mistakes: ["Pulling with arms", "Hinging at hips only"],
    alternatives: ["Machine Crunch", "Weighted Crunch"],
    progression: "3×15 → next pin",
    incrementKg: 2.5,
    home: {
      name: "Reverse Crunch",
      reps: "3×12–15",
      how: "Lie down, knees bent, roll the pelvis off the floor to bring knees to chest, lower slow. Exhale hard at the top — the same spine-curl the cable teaches, driven from below.",
    },
  },
  {
    id: "plank",
    name: "Plank",
    primary: "Abs",
    secondary: ["Lower Back"],
    equipment: "Bodyweight",
    videoUrl: yt("plank form"),
    cues: ["Straight line head to heels", "Squeeze glutes", "Tuck pelvis slightly"],
    mistakes: ["Hips sagging", "Butt in the air"],
    alternatives: ["RKC Plank", "Ab-wheel Rollout"],
    progression: "3×45 sec → 60 sec → weighted",
    incrementKg: 0,
    isBodyweight: true,
    home: {
      name: "RKC Plank",
      reps: "3×20–30 sec",
      how: "Already home-friendly. The harder version: squeeze glutes and fists, pull the elbows toward the toes without anything moving. 20 seconds done right should shake.",
    },
  },
];

// ------------------------------------------------------------
// Plan-engine metadata for the curated exercises above — kept as
// a map so the entries themselves stay untouched.
// ------------------------------------------------------------
const CURATED_TAGS: Record<string, Partial<Exercise>> = {
  "incline-db-press": { pattern: "h-push", difficulty: 1 },
  "incline-bb-press": { pattern: "h-push", difficulty: 2 },
  "flat-bb-bench": { pattern: "h-push", difficulty: 2 },
  "cable-fly-low-high": { pattern: "iso-chest", difficulty: 1 },
  dips: { pattern: "h-push", difficulty: 2, regressTo: "decline-push-up" },
  "db-lateral-raise": { pattern: "iso-side-delt", difficulty: 1 },
  "cable-lateral-raise": { pattern: "iso-side-delt", difficulty: 2 },
  "db-shoulder-press": { pattern: "v-push", difficulty: 1, avoidIf: ["overhead"] },
  "reverse-pec-deck": { pattern: "iso-rear-delt", difficulty: 1 },
  "face-pull": { pattern: "iso-rear-delt", difficulty: 1 },
  pullup: { pattern: "v-pull", difficulty: 2, equipment: "Pull-up Bar", regressTo: "negative-pull-up", progressTo: "archer-pull-up" },
  "lat-pulldown": { pattern: "v-pull", difficulty: 1 },
  "seated-cable-row": { pattern: "h-pull", difficulty: 1 },
  "single-arm-db-row": { pattern: "h-pull", difficulty: 1 },
  "straight-arm-pulldown": { pattern: "v-pull", difficulty: 1 },
  "ez-bar-curl": { pattern: "iso-biceps", difficulty: 1 },
  "incline-db-curl": { pattern: "iso-biceps", difficulty: 2 },
  "hammer-curl": { pattern: "iso-biceps", difficulty: 1 },
  "triceps-pushdown": { pattern: "iso-triceps", difficulty: 1 },
  "overhead-triceps-ext": { pattern: "iso-triceps", difficulty: 1, avoidIf: ["overhead"] },
  squat: { pattern: "squat", difficulty: 2, avoidIf: ["spine"] },
  "leg-press": { pattern: "squat", difficulty: 1 },
  rdl: { pattern: "hinge", difficulty: 2, avoidIf: ["spine"] },
  "leg-curl": { pattern: "iso-hams", difficulty: 1 },
  "leg-extension": { pattern: "iso-quads", difficulty: 1 },
  "calf-raise": { pattern: "iso-calves", difficulty: 1 },
  "hanging-knee-raise": { pattern: "core", difficulty: 2, equipment: "Pull-up Bar", regressTo: "lying-leg-raise" },
  "cable-crunch": { pattern: "core", difficulty: 1 },
  plank: { pattern: "core", difficulty: 1 },
};

export const EXERCISES: Exercise[] = [
  ...CURATED_EXERCISES.map((e) => ({ ...e, ...CURATED_TAGS[e.id] })),
  ...LIBRARY_EXERCISES,
].map((e) => ({ ...e, videoId: VIDEO_IDS[e.id] }));

// ------------------------------------------------------------
// Weekly plan — PPL×2 with weak-point bias.
// Extra volume for: upper chest, side delts, lats, rear delts, arms.
// Legs 1× heavy + spread maintenance. Sunday rest.
// ------------------------------------------------------------
const px = (
  exerciseId: string,
  workingSets: number,
  repsMin: number,
  repsMax: number,
  restSeconds: number,
  opts: { warmupSets?: number; notes?: string } = {},
): import("./types").PlannedExercise => ({
  exerciseId,
  warmupSets: opts.warmupSets ?? 0,
  workingSets,
  repsMin,
  repsMax,
  restSeconds,
  notes: opts.notes,
});

export const DEFAULT_PLAN: WorkoutDay[] = [
  {
    id: "push-a",
    weekday: 1, // Monday
    name: "Push A",
    focus: "Upper Chest + Side Delts",
    durationMin: 75,
    warmupMin: 8,
    exercises: [
      px("incline-db-press", 3, 8, 10, 120, { warmupSets: 2, notes: "Priority lift — keep elbows at 45°" }),
      px("flat-bb-bench", 3, 6, 8, 150, { warmupSets: 1, notes: "Strength focus. Milestone: 60 kg × 8" }),
      px("cable-fly-low-high", 3, 12, 15, 75, { notes: "Squeeze 2 sec at the top" }),
      px("db-lateral-raise", 4, 12, 15, 60, { notes: "4 sets — side delt priority" }),
      px("triceps-pushdown", 3, 10, 12, 75),
      px("overhead-triceps-ext", 2, 12, 15, 75),
    ],
  },
  {
    id: "pull-a",
    weekday: 2, // Tuesday
    name: "Pull A",
    focus: "Lats + Rear Delts",
    durationMin: 75,
    warmupMin: 8,
    exercises: [
      px("lat-pulldown", 3, 8, 10, 120, { warmupSets: 2, notes: "Milestone: 45 kg. Elbows down, not back" }),
      px("seated-cable-row", 3, 10, 12, 90),
      px("straight-arm-pulldown", 3, 12, 15, 75, { notes: "Pure lat — feel the stretch" }),
      px("face-pull", 3, 15, 20, 60, { notes: "Rear delts + shoulder health" }),
      px("ez-bar-curl", 3, 8, 10, 75),
      px("hammer-curl", 2, 10, 12, 60),
    ],
  },
  {
    id: "legs-a",
    weekday: 3, // Wednesday
    name: "Legs A",
    focus: "Quads + Hamstrings",
    durationMin: 70,
    warmupMin: 10,
    exercises: [
      px("squat", 3, 6, 8, 180, { warmupSets: 2, notes: "Brace hard, hit depth" }),
      px("rdl", 3, 8, 10, 120, { warmupSets: 1 }),
      px("leg-extension", 3, 12, 15, 75),
      px("leg-curl", 3, 12, 15, 75),
      px("calf-raise", 4, 12, 15, 60, { notes: "2-sec stretch at the bottom" }),
      px("hanging-knee-raise", 3, 10, 15, 60),
    ],
  },
  {
    id: "push-b",
    weekday: 4, // Thursday
    name: "Push B",
    focus: "Upper Chest volume + Delts",
    durationMin: 70,
    warmupMin: 8,
    exercises: [
      px("incline-bb-press", 3, 8, 10, 120, { warmupSets: 2, notes: "Touch upper chest, no bounce" }),
      px("db-shoulder-press", 3, 8, 10, 120, { warmupSets: 1 }),
      px("dips", 3, 8, 12, 90, { notes: "Lean forward for chest" }),
      px("cable-lateral-raise", 4, 12, 15, 60, { notes: "Constant tension — no swinging" }),
      px("reverse-pec-deck", 3, 12, 15, 60),
      px("overhead-triceps-ext", 3, 10, 12, 75),
    ],
  },
  {
    id: "pull-b",
    weekday: 5, // Friday
    name: "Pull B",
    focus: "Width + Arms",
    durationMin: 75,
    warmupMin: 8,
    exercises: [
      px("pullup", 3, 5, 8, 150, { warmupSets: 1, notes: "Assisted is fine — build to bodyweight" }),
      px("single-arm-db-row", 3, 8, 10, 90),
      px("lat-pulldown", 2, 12, 15, 90, { notes: "Lighter — perfect stretch and squeeze" }),
      px("face-pull", 3, 15, 20, 60),
      px("incline-db-curl", 3, 8, 10, 75, { notes: "Long-head stretch — arms priority" }),
      px("triceps-pushdown", 2, 12, 15, 60),
    ],
  },
  {
    id: "weak-point",
    weekday: 6, // Saturday
    name: "Weak-Point + Core",
    focus: "Delts, Upper Chest pump, Waist",
    durationMin: 55,
    warmupMin: 6,
    exercises: [
      px("db-lateral-raise", 4, 15, 20, 45, { notes: "Light pump work" }),
      px("cable-fly-low-high", 3, 12, 15, 60),
      px("reverse-pec-deck", 3, 15, 20, 45),
      px("cable-crunch", 3, 12, 15, 60),
      px("plank", 3, 45, 60, 60, { notes: "Reps = seconds held" }),
      px("leg-press", 3, 10, 12, 90, { notes: "Leg maintenance volume" }),
    ],
  },
  {
    id: "rest",
    weekday: 0, // Sunday
    name: "Rest",
    focus: "Recovery — walk, stretch, sleep",
    durationMin: 0,
    warmupMin: 0,
    isRest: true,
    exercises: [],
  },
];

// ------------------------------------------------------------
export const ACHIEVEMENTS: AchievementDef[] = [
  { id: "first-workout", icon: "🎬", name: "First Workout", desc: "Complete your first session" },
  { id: "first-pullup", icon: "🏅", name: "First Pull-up", desc: "Log a bodyweight pull-up" },
  { id: "workouts-10", icon: "🔟", name: "10 Workouts", desc: "Complete 10 sessions" },
  { id: "workouts-50", icon: "⚡", name: "50 Workouts", desc: "Complete 50 sessions" },
  { id: "workouts-100", icon: "💯", name: "100 Workouts", desc: "Complete 100 sessions" },
  { id: "streak-7", icon: "🔥", name: "7-Day Streak", desc: "Train every planned day for a week" },
  { id: "streak-30", icon: "🌋", name: "30-Day Streak", desc: "A full month without missing" },
  { id: "streak-180", icon: "👑", name: "6-Month Streak", desc: "Half a year of consistency" },
  { id: "bench-40", icon: "🏋️", name: "40 kg Bench", desc: "Bench press 40 kg" },
  { id: "bench-60", icon: "🦾", name: "60 kg Bench", desc: "Bench press 60 kg" },
  { id: "pulldown-45", icon: "🪽", name: "45 kg Pulldown", desc: "Lat pulldown 45 kg" },
  { id: "bf-15", icon: "📉", name: "15% Body Fat", desc: "Measure at or below 15%" },
  { id: "bf-12", icon: "🎯", name: "12% Body Fat", desc: "Hit the recomposition target" },
  { id: "bf-10", icon: "💎", name: "10% Body Fat", desc: "Elite leanness" },
  { id: "protein-week", icon: "🍗", name: "Protein Week", desc: "Hit protein goal 7 days in a row" },
  { id: "photo-3", icon: "📸", name: "Transformation Log", desc: "3 months of progress photos" },
];

// ------------------------------------------------------------
const thisMonth = () => new Date().toISOString().slice(0, 7);
const nextMonth = () => {
  const d = new Date();
  d.setMonth(d.getMonth() + 1);
  return d.toISOString().slice(0, 7);
};

// generic starter goals — the plan wizard replaces these with
// goal-specific ones; only explore-without-setup users keep them
export const DEFAULT_ROADMAP: RoadmapGoal[] = [
  { id: "m1-first-workouts", month: thisMonth(), label: "Complete your first 10 workouts", done: false },
  { id: "m1-photos", month: thisMonth(), label: "Take first progress photos", done: false },
  { id: "m1-protein", month: thisMonth(), label: "Hit your protein goal 5 days in a row", done: false },
  { id: "m2-consistency", month: nextMonth(), label: "A full month without missing a planned day", done: false },
  { id: "m2-progress", month: nextMonth(), label: "Add weight or reps on every main lift", done: false },
];

export const DEFAULT_PROFILE: Profile = {
  name: "Athlete",
  heightCm: 172,
  birthYear: 2000,
  phase: "General Fitness",
  targetWeightKg: 70,
  targetBodyFatPct: 15,
  proteinGoalG: 120,
  waterGoalMl: 3000,
  stepsGoal: 8000,
  sleepGoalH: 8,
  nextMilestone: "Complete your first 10 workouts",
};

export function createInitialState(): AppState {
  return {
    version: 1,
    onboarded: false,
    profile: DEFAULT_PROFILE,
    plan: DEFAULT_PLAN,
    sessions: [],
    // nothing pre-filled: the wizard seeds the first weight, everything else is theirs to log
    measurements: [],
    foodLog: [],
    recovery: [],
    journal: [],
    photos: [],
    roadmap: DEFAULT_ROADMAP,
    activities: [],
    unlocked: {},
  };
}

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);
